package mx.unam.ciencias.myp.server;

public enum MessageType {
    IDENTIFY, STATUS, USERS, MESSAGE, PUBLICMESSAGE, CREATEROOM, INVITE,
    JOINROOM, ROOMESSAGE, LEAVEROOM, DISCONNECT, NEWUSER, MESSAGEFROM,
    PUBLICMESSAGEFROM, JOINEDROOM, ROOMESSAGEFROM, DISCONNECTED, ERROR,
    WARNING, INVALID;
}
