package mx.unam.ciencias.myp.server;

public enum MessageType {
    IDENTIFY, STATUS, USERS, MESSAGE, PUBLICMESSAGE, CREATEROOM, INVITE,
    JOINROOM, ROOMESSAGE, LEAVEROOM, DISCONNECT, NEWUSER, USERLIST,
    MESSAGEFROM, PUBLICMESSAGEFROM, INVITEFROM, JOINEDFROM, ROOMESSAGEFROM,
    LEFTROOM, DISCONNECTED, ERROR, WARNING, INFO, INVALID;
}
